// gps.js - modulo isolado de geolocalizacao
(function(){'use strict';
const cfg=window.ChecklistGPSConfig;if(!cfg)return console.error('GPS: configuracao ausente.');
const select=document.getElementById('select-local'),controls=document.querySelector('.controls-top');if(!select||!controls)return;
const vistoriaId=cfg.getVistoriaId(),cache=new Map(),key=`checklist_gps_pendente_${vistoriaId||'sem_id'}`;let leitura=new URLSearchParams(location.search).get('modo')==='leitura';
const box=document.createElement('section');box.style.cssText='margin:10px 0 16px;padding:14px;border:1px solid #d8e0e8;border-radius:10px;background:#fff';controls.insertAdjacentElement('afterend',box);
const headers=(json=false)=>Object.assign({apikey:cfg.supabaseKey,Authorization:`Bearer ${cfg.supabaseKey}`,Accept:'application/json'},json?{'Content-Type':'application/json'}:{});
const atual=()=>select.value||'ALL';const localId=n=>[...document.querySelectorAll('.sector')].find(s=>s.dataset.setor===n)?.dataset.localId||null;
const fmt=v=>v?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'';
const pend=()=>{try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return {}}};
function gravaPendente(r){const p=pend();p[r.local_nome_snapshot]=r;localStorage.setItem(key,JSON.stringify(p));cache.set(r.local_nome_snapshot,{...r,pendente:true})}
function limpaPendente(n){const p=pend();delete p[n];Object.keys(p).length?localStorage.setItem(key,JSON.stringify(p)):localStorage.removeItem(key)}
function mergePend(){Object.values(pend()).forEach(r=>cache.set(r.local_nome_snapshot,{...r,pendente:true}))}
const esc=t=>{const d=document.createElement('div');d.textContent=t||'';return d.innerHTML};
function render(){const n=atual();if(n==='ALL'){box.style.display='none';return}box.style.display='block';const r=cache.get(n),baixa=r&&Number(r.precisao_metros)>100;box.innerHTML=`<div style="font-weight:800">📍 Localização da vistoria</div><div style="margin-top:5px;font-weight:700">${esc(n)}</div><div style="margin-top:6px">${r?(r.pendente?'🟠 GPS registrado no aparelho, aguardando sincronização':'🟢 GPS registrado'):'Localização ainda não registrada.'}</div>${r?`<div style="margin-top:6px;color:#475569">Precisão: ± ${Math.round(Number(r.precisao_metros||0))} m${baixa?' <strong style="color:#a16207">• precisão baixa</strong>':''}<br>Capturado em: ${fmt(r.capturado_em)}</div>`:''}${leitura?'':`<button id="btn-gps-local" type="button" style="margin-top:10px;min-height:42px;padding:9px 14px;border:0;border-radius:8px;background:#0b6aa6;color:#fff;font-weight:700">${r?'📍 Atualizar localização':'📍 Registrar localização'}</button>`}<div id="gps-msg" style="margin-top:8px;font-size:13px;color:#64748b"></div>`;document.getElementById('btn-gps-local')?.addEventListener('click',capturar)}
async function salvar(r){const u=`${cfg.supabaseUrl}/rest/v1/checklist_vistoria_locais?on_conflict=vistoria_id,local_nome_snapshot`;const x=await fetch(u,{method:'POST',headers:{...headers(true),Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(r)});if(!x.ok)throw new Error(await x.text());const d=await x.json();return d?.[0]||r}
function mensagemErro(e){return e?.code===1?'Permissão de localização negada. Autorize a localização no navegador.':e?.code===2?'Não foi possível determinar sua localização.':e?.code===3?'O GPS demorou demais para responder. Tente novamente em local mais aberto.':'Não foi possível obter a localização.'}
function capturar(){const n=atual(),msg=document.getElementById('gps-msg'),btn=document.getElementById('btn-gps-local');if(!vistoriaId){msg.textContent='Vistoria sem identificação.';return}if(!navigator.geolocation){msg.textContent='Este navegador não oferece geolocalização.';return}btn.disabled=true;btn.textContent='Obtendo localização...';msg.textContent='Aguardando o GPS do aparelho...';navigator.geolocation.getCurrentPosition(async p=>{const agora=new Date().toISOString();const r={vistoria_id:vistoriaId,local_id:localId(n),local_nome_snapshot:n,latitude:p.coords.latitude,longitude:p.coords.longitude,precisao_metros:p.coords.accuracy??null,capturado_em:agora,atualizado_em:agora};try{if(!navigator.onLine)throw new Error('offline');const s=await salvar(r);cache.set(n,s);limpaPendente(n)}catch(e){gravaPendente(r);console.warn('GPS pendente de sincronizacao.',e)}render()},e=>{btn.disabled=false;btn.textContent=cache.has(n)?'📍 Atualizar localização':'📍 Registrar localização';msg.textContent=mensagemErro(e)},{enableHighAccuracy:true,timeout:20000,maximumAge:0})}
async function carregar(){if(vistoriaId)try{let x=await fetch(`${cfg.supabaseUrl}/rest/v1/checklist_vistoria_locais?vistoria_id=eq.${encodeURIComponent(vistoriaId)}&select=*`,{headers:headers()});if(x.ok)(await x.json()).forEach(r=>cache.set(r.local_nome_snapshot,r));x=await fetch(`${cfg.supabaseUrl}/rest/v1/checklist_vistorias?id=eq.${encodeURIComponent(vistoriaId)}&select=status`,{headers:headers()});if(x.ok&&((await x.json())?.[0]?.status==='FINALIZADA'))leitura=true}catch(e){console.warn('GPS: consulta online indisponivel.',e)}mergePend();render()}
async function sincronizar(){if(!vistoriaId||!navigator.onLine)return;for(const[n,r]of Object.entries(pend()))try{const s=await salvar(r);cache.set(n,s);limpaPendente(n)}catch(e){console.warn('GPS ainda pendente:',n,e)}render()}
select.addEventListener('change',render);window.addEventListener('online',sincronizar);carregar().then(sincronizar);
})();